-- veil-forum PostgreSQL baseline schema (migration 0001).
--
-- This replaces the SQLite migration history (001..011). PostgreSQL installs
-- start from this single baseline; existing SQLite installations are moved over
-- with the `veil-forum-import` helper, which writes into this schema.
--
-- Mapping decisions:
--   * `INTEGER PRIMARY KEY AUTOINCREMENT` -> `BIGINT GENERATED BY DEFAULT AS IDENTITY`
--     so identifiers stay i64 on the Rust side. BY DEFAULT (not ALWAYS) keeps
--     explicit ids insertable, which the importer relies on.
--   * `INTEGER` 0/1 flags -> native `BOOLEAN`.
--   * RFC3339 `TEXT` timestamps -> `TIMESTAMPTZ`.
--   * SQLite foreign key actions are repeated explicitly; PostgreSQL defaults
--     to NO ACTION.
--   * FTS5 (`posts_fts`, trigram tokenizer) and its triggers are replaced by
--     pg_trgm GIN indexes, which also serve the short-query LIKE path.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    is_admin      BOOLEAN NOT NULL DEFAULT FALSE,
    is_banned     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ NOT NULL,
    locale        TEXT NOT NULL DEFAULT 'zh'
);

CREATE TABLE boards (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            TEXT NOT NULL UNIQUE,
    name            TEXT NOT NULL,
    description     TEXT NOT NULL DEFAULT '',
    allow_anonymous BOOLEAN NOT NULL DEFAULT TRUE,
    guest_readable  BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL,
    name_i18n       TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE configs (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE invite_codes (
    code       TEXT PRIMARY KEY,
    created_by BIGINT NOT NULL REFERENCES users(id),
    used_by    BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ,
    max_uses   BIGINT NOT NULL DEFAULT 1,
    use_count  BIGINT NOT NULL DEFAULT 0,
    expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    revoked_by BIGINT REFERENCES users(id),
    note       TEXT NOT NULL DEFAULT ''
);

CREATE TABLE threads (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id           BIGINT NOT NULL REFERENCES boards(id) ON DELETE CASCADE,
    title              TEXT NOT NULL,
    author_id          BIGINT NOT NULL REFERENCES users(id),
    is_pinned          BOOLEAN NOT NULL DEFAULT FALSE,
    is_locked          BOOLEAN NOT NULL DEFAULT FALSE,
    reply_count        BIGINT NOT NULL DEFAULT 0,
    last_reply_at      TIMESTAMPTZ NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL,
    deleted_at         TIMESTAMPTZ,
    deleted_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE posts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id          BIGINT NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
    board_id           BIGINT NOT NULL REFERENCES boards(id),
    author_id          BIGINT NOT NULL REFERENCES users(id),
    is_anonymous       BOOLEAN NOT NULL DEFAULT FALSE,
    content_md         TEXT NOT NULL,
    content_html       TEXT NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL,
    parent_post_id     BIGINT REFERENCES posts(id) ON DELETE SET NULL,
    deleted_at         TIMESTAMPTZ,
    deleted_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE sessions (
    id           TEXT PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at   TIMESTAMPTZ NOT NULL,
    expires_at   TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ
);

CREATE TABLE audit_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action        TEXT NOT NULL,
    target_type   TEXT,
    target_id     BIGINT,
    success       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL,
    metadata      TEXT
);

CREATE TABLE roles (
    name TEXT PRIMARY KEY CHECK (name IN ('owner', 'admin', 'moderator'))
);

INSERT INTO roles(name) VALUES ('owner'), ('admin'), ('moderator')
ON CONFLICT (name) DO NOTHING;

CREATE TABLE user_roles (
    user_id            BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_name          TEXT NOT NULL REFERENCES roles(name) ON DELETE CASCADE,
    granted_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at         TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (user_id, role_name)
);

CREATE TABLE board_moderators (
    board_id           BIGINT NOT NULL REFERENCES boards(id) ON DELETE CASCADE,
    user_id            BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    granted_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at         TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (board_id, user_id)
);

CREATE TABLE reports (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id    BIGINT REFERENCES users(id) ON DELETE SET NULL,
    target_type         TEXT NOT NULL CHECK (target_type IN ('post', 'thread', 'user')),
    target_id           BIGINT NOT NULL,
    reason              TEXT NOT NULL,
    status              TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved', 'dismissed')),
    resolved_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    resolution_note     TEXT,
    created_at          TIMESTAMPTZ NOT NULL,
    resolved_at         TIMESTAMPTZ
);

CREATE INDEX idx_threads_board_order
    ON threads (board_id, is_pinned DESC, last_reply_at DESC, id DESC);
CREATE INDEX idx_posts_thread ON posts (thread_id, id ASC);
CREATE INDEX idx_sessions_user ON sessions (user_id);
CREATE INDEX idx_sessions_expiry ON sessions (expires_at, last_seen_at);
CREATE INDEX idx_audit_created ON audit_logs (created_at DESC);
CREATE INDEX idx_posts_parent ON posts (parent_post_id);
CREATE INDEX idx_posts_thread_parent ON posts (thread_id, parent_post_id);
CREATE INDEX idx_user_roles_role ON user_roles (role_name, user_id);
CREATE INDEX idx_board_moderators_user ON board_moderators (user_id, board_id);
CREATE INDEX idx_reports_status_created ON reports (status, created_at DESC);
CREATE INDEX idx_reports_target ON reports (target_type, target_id);
CREATE INDEX idx_posts_visible_thread ON posts (thread_id, deleted_at, id ASC);
CREATE INDEX idx_threads_visible_board
    ON threads (board_id, deleted_at, is_pinned DESC, last_reply_at DESC, id DESC);
CREATE INDEX idx_invite_codes_status
    ON invite_codes (revoked_at, expires_at, use_count, max_uses);

-- Search: trigram indexes accelerate both `ILIKE '%term%'` (all query lengths
-- of three or more characters) and similarity ranking, for Latin and CJK text
-- alike. This replaces the FTS5 content table and its three sync triggers.
CREATE INDEX idx_posts_content_trgm ON posts USING gin (content_md gin_trgm_ops);
CREATE INDEX idx_threads_title_trgm ON threads USING gin (title gin_trgm_ops);
