use argon2::{
    password_hash::{phc::PasswordHash, PasswordHasher, PasswordVerifier},
    Argon2,
};
use sha2::{Digest, Sha256};
use std::sync::{Arc, OnceLock};
use tokio::sync::Semaphore;

fn password_gate() -> &'static Arc<Semaphore> {
    static GATE: OnceLock<Arc<Semaphore>> = OnceLock::new();
    GATE.get_or_init(|| Arc::new(Semaphore::new(8)))
}

pub fn digest_token(token: &str) -> String {
    hex::encode(Sha256::digest(token.as_bytes()))
}

/// Argon2id with 64 MiB, 3 iterations and 4 lanes. The salt is generated by
/// the hasher from the operating system RNG and travels in the PHC string, so
/// hashes written by earlier releases keep verifying.
pub fn hash_password(pw: &str) -> anyhow::Result<String> {
    let argon2 = Argon2::new(
        argon2::Algorithm::Argon2id,
        argon2::Version::V0x13,
        argon2::Params::new(64 * 1024, 3, 4, Some(32)).unwrap(),
    );
    let hash = argon2
        .hash_password(pw.as_bytes())
        .map_err(|e| anyhow::anyhow!("{}", e))?
        .to_string();
    Ok(hash)
}
pub fn verify_password(hash: &str, pw: &str) -> bool {
    let parsed = match PasswordHash::new(hash) {
        Ok(h) => h,
        Err(_) => return false,
    };
    Argon2::default()
        .verify_password(pw.as_bytes(), &parsed)
        .is_ok()
}

pub const PASSWORD_MIN_CHARS: usize = 15;
pub const PASSWORD_MAX_CHARS: usize = 128;

pub fn validate_password(password: &str, user_inputs: &[&str]) -> bool {
    let length = password.chars().count();
    if !(PASSWORD_MIN_CHARS..=PASSWORD_MAX_CHARS).contains(&length) {
        return false;
    }
    // Reuse Dropbox's maintained estimator instead of inventing composition or
    // breach-list rules. User-specific context prevents names and usernames
    // from supplying most of the apparent entropy.
    zxcvbn::zxcvbn(password, user_inputs).score() >= zxcvbn::Score::Three
}

pub async fn hash_password_blocking(pw: String) -> anyhow::Result<String> {
    let _permit = password_gate()
        .acquire()
        .await
        .map_err(|_| anyhow::anyhow!("password gate closed"))?;
    tokio::task::spawn_blocking(move || hash_password(&pw)).await?
}

pub async fn verify_password_blocking(hash: String, pw: String) -> bool {
    let Ok(_permit) = password_gate().acquire().await else {
        return false;
    };
    tokio::task::spawn_blocking(move || verify_password(&hash, &pw))
        .await
        .unwrap_or(false)
}

pub async fn dummy_password_hash() -> anyhow::Result<&'static str> {
    static HASH: OnceLock<String> = OnceLock::new();
    if let Some(hash) = HASH.get() {
        return Ok(hash);
    }
    let mut bytes = [0u8; 32];
    rand::Rng::fill_bytes(&mut rand::rng(), &mut bytes);
    let random = hex::encode(bytes);
    let hash = hash_password_blocking(random).await?;
    Ok(HASH.get_or_init(|| hash))
}
pub async fn ensure_admin(pool: &sqlx::PgPool) -> anyhow::Result<()> {
    let cnt: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM users")
        .fetch_one(pool)
        .await?;
    if cnt.0 != 0 {
        return Ok(());
    }
    let password = std::env::var("VEIL_ADMIN_PASSWORD").map_err(|_| {
        anyhow::anyhow!("empty database requires VEIL_ADMIN_PASSWORD for first administrator setup")
    })?;
    if !validate_password(&password, &["admin", "veil-forum"]) {
        anyhow::bail!("VEIL_ADMIN_PASSWORD must be 15-128 characters and sufficiently strong");
    }
    let h = hash_password_blocking(password).await?;
    let created_at = chrono::Utc::now();
    let admin_id = sqlx::query_scalar::<_, i64>(
        "INSERT INTO users(username,password_hash,is_admin,created_at) VALUES($1,$2,TRUE,$3) RETURNING id",
    )
    .bind("admin")
    .bind(h)
    .bind(created_at)
    .fetch_one(pool)
    .await?;
    // Store migrations run before first-run initialization, so the normalized
    // role tables already exist. The bootstrap account must be an owner rather
    // than relying on the legacy is_admin compatibility flag.
    sqlx::query(
        "INSERT INTO user_roles(user_id,role_name,granted_by_user_id,created_at) VALUES($1,'owner',NULL,$2)",
    )
    .bind(admin_id)
    .bind(created_at)
    .execute(pool)
    .await?;
    Ok(())
}
