use argon2::{
    password_hash::{phc::PasswordHash, PasswordHasher, PasswordVerifier},
    Argon2,
};

/// Argon2id with 64 MiB, 3 iterations and 4 lanes. The salt is generated by
/// the hasher from the operating system RNG and travels in the PHC string, so
/// hashes written by earlier releases keep verifying.
pub fn hash_password(pw: &str) -> anyhow::Result<String> {
    let argon2 = Argon2::new(
        argon2::Algorithm::Argon2id,
        argon2::Version::V0x13,
        argon2::Params::new(64 * 1024, 3, 4, Some(32)).unwrap(),
    );
    let hash = argon2
        .hash_password(pw.as_bytes())
        .map_err(|e| anyhow::anyhow!("{}", e))?
        .to_string();
    Ok(hash)
}
pub fn verify_password(hash: &str, pw: &str) -> bool {
    let parsed = match PasswordHash::new(hash) {
        Ok(h) => h,
        Err(_) => return false,
    };
    Argon2::default()
        .verify_password(pw.as_bytes(), &parsed)
        .is_ok()
}
pub async fn ensure_admin(pool: &sqlx::PgPool) -> anyhow::Result<()> {
    let cnt: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM users")
        .fetch_one(pool)
        .await?;
    if cnt.0 != 0 {
        return Ok(());
    }
    let password = std::env::var("VEIL_ADMIN_PASSWORD").map_err(|_| {
        anyhow::anyhow!("empty database requires VEIL_ADMIN_PASSWORD for first administrator setup")
    })?;
    if password.chars().count() < 12 || password.chars().count() > 128 {
        anyhow::bail!("VEIL_ADMIN_PASSWORD must contain 12-128 characters");
    }
    let h = hash_password(&password)?;
    let created_at = chrono::Utc::now();
    let admin_id = sqlx::query_scalar::<_, i64>(
        "INSERT INTO users(username,password_hash,is_admin,created_at) VALUES($1,$2,TRUE,$3) RETURNING id",
    )
    .bind("admin")
    .bind(h)
    .bind(created_at)
    .fetch_one(pool)
    .await?;
    // Store migrations run before first-run initialization, so the normalized
    // role tables already exist. The bootstrap account must be an owner rather
    // than relying on the legacy is_admin compatibility flag.
    sqlx::query(
        "INSERT INTO user_roles(user_id,role_name,granted_by_user_id,created_at) VALUES($1,'owner',NULL,$2)",
    )
    .bind(admin_id)
    .bind(created_at)
    .execute(pool)
    .await?;
    Ok(())
}
