//! One-shot SQLite to PostgreSQL importer.
//!
//! This is the only target that links the SQLite driver; the server binary
//! talks to PostgreSQL exclusively. It is meant to run once per installation
//! during the upgrade to the PostgreSQL backend:
//!
//! ```text
//! veil-forum-import --sqlite /var/lib/veil-forum/forum.db \
//!                   --database-url postgres:///veil_forum?host=/var/run/postgresql
//! ```
//!
//! Behaviour:
//!   * The PostgreSQL schema is created by the embedded migrations when missing.
//!   * Rows are copied with their original identifiers, in foreign-key order.
//!   * Timestamps are parsed from every historical SQLite text format and stored
//!     as `TIMESTAMPTZ`.
//!   * Identity sequences are advanced past the imported identifiers, so new
//!     rows continue where the old database stopped.
//!   * A per-table row-count reconciliation runs at the end; any mismatch is a
//!     hard error.
//!
//! Safety:
//!   * The source SQLite file is opened read-only and never modified.
//!   * The target is only written when it has no forum data, or when `--force`
//!     is passed (which truncates the forum tables first).
//!   * `--dry-run` reports what would be copied and exits.

use anyhow::Context;
use chrono::{DateTime, NaiveDateTime, Utc};
use sqlx::sqlite::{SqliteConnectOptions, SqlitePoolOptions as SqlitePoolOptionsT};
use sqlx::{PgPool, Row};
use std::str::FromStr;

/// Tables copied from the source database, in foreign-key order.
const TABLES: &[&str] = &[
    "users",
    "boards",
    "configs",
    "invite_codes",
    "threads",
    "posts",
    "sessions",
    "audit_logs",
    "user_roles",
    "board_moderators",
    "reports",
];

/// Tables with a `BIGINT GENERATED BY DEFAULT AS IDENTITY` primary key.
const IDENTITY_TABLES: &[&str] = &[
    "users",
    "boards",
    "threads",
    "posts",
    "audit_logs",
    "reports",
];

/// Parse every timestamp format historical SQLite databases contain:
/// RFC3339 with nanoseconds, RFC3339 with offsets, second precision, the
/// space-separated legacy form, and both with or without a trailing `Z`.
pub fn parse_legacy_time(value: &str) -> anyhow::Result<DateTime<Utc>> {
    let s = value.trim();
    if let Ok(dt) = DateTime::parse_from_rfc3339(s) {
        return Ok(dt.with_timezone(&Utc));
    }
    for format in [
        "%Y-%m-%dT%H:%M:%S%.fZ",
        "%Y-%m-%dT%H:%M:%SZ",
        "%Y-%m-%d %H:%M:%S%.f",
        "%Y-%m-%d %H:%M:%S",
        "%Y-%m-%d %H:%M:%S%.fZ",
        "%Y-%m-%d %H:%M:%SZ",
    ] {
        if let Ok(dt) = NaiveDateTime::parse_from_str(s, format) {
            return Ok(dt.and_utc());
        }
    }
    Err(anyhow::anyhow!("invalid timestamp: {value:?}"))
}

struct Options {
    sqlite_path: String,
    database_url: String,
    dry_run: bool,
    force: bool,
    include_sessions: bool,
}

fn parse_options() -> anyhow::Result<Options> {
    let mut sqlite_path = None;
    let mut database_url = std::env::var("DATABASE_URL").ok();
    let mut dry_run = false;
    let mut force = false;
    let mut include_sessions = false;
    let mut args = std::env::args().skip(1);
    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--sqlite" => {
                sqlite_path = Some(
                    args.next()
                        .context("--sqlite requires a path to the SQLite database")?,
                )
            }
            "--database-url" => {
                database_url = Some(
                    args.next()
                        .context("--database-url requires a connection string")?,
                )
            }
            "--dry-run" => dry_run = true,
            "--force" => force = true,
            "--include-sessions" => include_sessions = true,
            "--help" | "-h" => {
                println!(
                    "usage: veil-forum-import --sqlite PATH [--database-url URL] [--dry-run] [--force] [--include-sessions]"
                );
                std::process::exit(0);
            }
            other => anyhow::bail!("unknown argument {other:?}; try --help"),
        }
    }
    Ok(Options {
        sqlite_path: sqlite_path.context("--sqlite PATH is required")?,
        database_url: database_url
            .unwrap_or_else(|| "postgres:///veil_forum?host=/var/run/postgresql".to_string()),
        dry_run,
        force,
        include_sessions,
    })
}

// Every accessor decodes `Option<T>`: the SQLite driver maps NULL to a zero
// value when a bare integer is requested, which would turn a nullable foreign
// key such as `deleted_by_user_id` into 0 and break the copy.

/// SQLite stores booleans as 0/1 and may return them as either integer or text.
fn bool_at(row: &sqlx::sqlite::SqliteRow, name: &str) -> bool {
    if let Some(value) = row.try_get::<Option<i64>, _>(name).ok().flatten() {
        return value != 0;
    }
    row.try_get::<Option<String>, _>(name)
        .ok()
        .flatten()
        .map(|value| value != "0" && !value.is_empty())
        .unwrap_or(false)
}

fn i64_at(row: &sqlx::sqlite::SqliteRow, name: &str) -> Option<i64> {
    row.try_get::<Option<i64>, _>(name).ok().flatten()
}

fn string_at(row: &sqlx::sqlite::SqliteRow, name: &str) -> Option<String> {
    row.try_get::<Option<String>, _>(name).ok().flatten()
}

fn time_at(row: &sqlx::sqlite::SqliteRow, name: &str) -> anyhow::Result<Option<DateTime<Utc>>> {
    match string_at(row, name) {
        Some(value) if !value.trim().is_empty() => Ok(Some(
            parse_legacy_time(&value).with_context(|| format!("column {name}"))?,
        )),
        _ => Ok(None),
    }
}

async fn count_rows_sqlite(pool: &sqlx::SqlitePool, table: &str) -> anyhow::Result<i64> {
    let sql = format!("SELECT COUNT(*) FROM {table}");
    Ok(sqlx::query_scalar::<_, i64>(&sql).fetch_one(pool).await?)
}

async fn count_rows_postgres(pool: &PgPool, table: &str) -> anyhow::Result<i64> {
    let sql = format!("SELECT COUNT(*) FROM {table}");
    Ok(sqlx::query_scalar::<_, i64>(&sql).fetch_one(pool).await?)
}

async fn target_has_data(pool: &PgPool) -> anyhow::Result<bool> {
    let users: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM users")
        .fetch_one(pool)
        .await?;
    if users > 0 {
        return Ok(true);
    }
    let posts: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM posts")
        .fetch_one(pool)
        .await?;
    Ok(posts > 0)
}

async fn truncate_forum_tables(target: &mut sqlx::PgConnection) -> anyhow::Result<()> {
    sqlx::raw_sql(
        "TRUNCATE users, boards, configs, invite_codes, threads, posts, sessions, \
         audit_logs, user_roles, board_moderators, reports RESTART IDENTITY CASCADE",
    )
    .execute(&mut *target)
    .await?;
    Ok(())
}

async fn import_users(
    source: &sqlx::SqlitePool,
    target: &mut sqlx::PgConnection,
) -> anyhow::Result<u64> {
    let rows = sqlx::query("SELECT * FROM users").fetch_all(source).await?;
    let mut copied = 0u64;
    for row in &rows {
        sqlx::query(
            "INSERT INTO users(id,username,password_hash,is_admin,is_banned,created_at,locale) \
             VALUES($1,$2,$3,$4,$5,$6,$7)",
        )
        .bind(i64_at(row, "id"))
        .bind(string_at(row, "username").unwrap_or_default())
        .bind(string_at(row, "password_hash").unwrap_or_default())
        .bind(bool_at(row, "is_admin"))
        .bind(bool_at(row, "is_banned"))
        .bind(time_at(row, "created_at")?.unwrap_or_else(Utc::now))
        .bind(string_at(row, "locale").unwrap_or_else(|| "zh".to_string()))
        .execute(&mut *target)
        .await?;
        copied += 1;
    }
    Ok(copied)
}

async fn import_boards(
    source: &sqlx::SqlitePool,
    target: &mut sqlx::PgConnection,
) -> anyhow::Result<u64> {
    let rows = sqlx::query("SELECT * FROM boards")
        .fetch_all(source)
        .await?;
    let mut copied = 0u64;
    for row in &rows {
        sqlx::query(
            "INSERT INTO boards(id,slug,name,description,allow_anonymous,guest_readable,created_at,name_i18n) \
             VALUES($1,$2,$3,$4,$5,$6,$7,$8)",
        )
        .bind(i64_at(row, "id"))
        .bind(string_at(row, "slug").unwrap_or_default())
        .bind(string_at(row, "name").unwrap_or_default())
        .bind(string_at(row, "description").unwrap_or_default())
        .bind(bool_at(row, "allow_anonymous"))
        .bind(bool_at(row, "guest_readable"))
        .bind(time_at(row, "created_at")?.unwrap_or_else(Utc::now))
        .bind(string_at(row, "name_i18n").unwrap_or_else(|| "{}".to_string()))
        .execute(&mut *target)
        .await?;
        copied += 1;
    }
    Ok(copied)
}

async fn import_configs(
    source: &sqlx::SqlitePool,
    target: &mut sqlx::PgConnection,
) -> anyhow::Result<u64> {
    let rows = sqlx::query("SELECT * FROM configs")
        .fetch_all(source)
        .await?;
    let mut copied = 0u64;
    for row in &rows {
        sqlx::query("INSERT INTO configs(key,value) VALUES($1,$2) ON CONFLICT (key) DO NOTHING")
            .bind(string_at(row, "key").unwrap_or_default())
            .bind(string_at(row, "value").unwrap_or_default())
            .execute(&mut *target)
            .await?;
        copied += 1;
    }
    Ok(copied)
}

async fn import_invite_codes(
    source: &sqlx::SqlitePool,
    target: &mut sqlx::PgConnection,
) -> anyhow::Result<u64> {
    let rows = sqlx::query("SELECT * FROM invite_codes")
        .fetch_all(source)
        .await?;
    let mut copied = 0u64;
    for row in &rows {
        sqlx::query(
            "INSERT INTO invite_codes(code,created_by,used_by,created_at,used_at,max_uses,use_count,expires_at,revoked_at,revoked_by,note) \
             VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)",
        )
        .bind(string_at(row, "code").unwrap_or_default())
        .bind(i64_at(row, "created_by"))
        .bind(i64_at(row, "used_by"))
        .bind(time_at(row, "created_at")?.unwrap_or_else(Utc::now))
        .bind(time_at(row, "used_at")?)
        .bind(i64_at(row, "max_uses").unwrap_or(1))
        .bind(i64_at(row, "use_count").unwrap_or(0))
        .bind(time_at(row, "expires_at")?)
        .bind(time_at(row, "revoked_at")?)
        .bind(i64_at(row, "revoked_by"))
        .bind(string_at(row, "note").unwrap_or_default())
        .execute(&mut *target)
        .await?;
        copied += 1;
    }
    Ok(copied)
}

async fn import_threads(
    source: &sqlx::SqlitePool,
    target: &mut sqlx::PgConnection,
) -> anyhow::Result<u64> {
    let rows = sqlx::query("SELECT * FROM threads")
        .fetch_all(source)
        .await?;
    let mut copied = 0u64;
    for row in &rows {
        sqlx::query(
            "INSERT INTO threads(id,board_id,title,author_id,is_pinned,is_locked,reply_count,last_reply_at,created_at,deleted_at,deleted_by_user_id) \
             VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)",
        )
        .bind(i64_at(row, "id"))
        .bind(i64_at(row, "board_id"))
        .bind(string_at(row, "title").unwrap_or_default())
        .bind(i64_at(row, "author_id"))
        .bind(bool_at(row, "is_pinned"))
        .bind(bool_at(row, "is_locked"))
        .bind(i64_at(row, "reply_count").unwrap_or(0))
        .bind(time_at(row, "last_reply_at")?.unwrap_or_else(Utc::now))
        .bind(time_at(row, "created_at")?.unwrap_or_else(Utc::now))
        .bind(time_at(row, "deleted_at")?)
        .bind(i64_at(row, "deleted_by_user_id"))
        .execute(&mut *target)
        .await?;
        copied += 1;
    }
    Ok(copied)
}

async fn import_posts(
    source: &sqlx::SqlitePool,
    target: &mut sqlx::PgConnection,
) -> anyhow::Result<u64> {
    let rows = sqlx::query("SELECT * FROM posts").fetch_all(source).await?;
    let mut copied = 0u64;
    for row in &rows {
        sqlx::query(
            "INSERT INTO posts(id,thread_id,board_id,author_id,is_anonymous,content_md,content_html,created_at,parent_post_id,deleted_at,deleted_by_user_id) \
             VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)",
        )
        .bind(i64_at(row, "id"))
        .bind(i64_at(row, "thread_id"))
        .bind(i64_at(row, "board_id"))
        .bind(i64_at(row, "author_id"))
        .bind(bool_at(row, "is_anonymous"))
        .bind(string_at(row, "content_md").unwrap_or_default())
        .bind(string_at(row, "content_html").unwrap_or_default())
        .bind(time_at(row, "created_at")?.unwrap_or_else(Utc::now))
        .bind(i64_at(row, "parent_post_id"))
        .bind(time_at(row, "deleted_at")?)
        .bind(i64_at(row, "deleted_by_user_id"))
        .execute(&mut *target)
        .await?;
        copied += 1;
    }
    Ok(copied)
}

async fn import_sessions(
    source: &sqlx::SqlitePool,
    target: &mut sqlx::PgConnection,
) -> anyhow::Result<u64> {
    let rows = sqlx::query("SELECT * FROM sessions")
        .fetch_all(source)
        .await?;
    let mut copied = 0u64;
    for row in &rows {
        sqlx::query(
            "INSERT INTO sessions(id,user_id,created_at,expires_at,last_seen_at) VALUES($1,$2,$3,$4,$5)",
        )
        .bind(string_at(row, "id").unwrap_or_default())
        .bind(i64_at(row, "user_id"))
        .bind(time_at(row, "created_at")?.unwrap_or_else(Utc::now))
        .bind(time_at(row, "expires_at")?.unwrap_or_else(Utc::now))
        .bind(time_at(row, "last_seen_at")?)
        .execute(&mut *target)
        .await?;
        copied += 1;
    }
    Ok(copied)
}

async fn import_audit_logs(
    source: &sqlx::SqlitePool,
    target: &mut sqlx::PgConnection,
) -> anyhow::Result<u64> {
    let rows = sqlx::query("SELECT * FROM audit_logs")
        .fetch_all(source)
        .await?;
    let mut copied = 0u64;
    for row in &rows {
        sqlx::query(
            "INSERT INTO audit_logs(id,actor_user_id,action,target_type,target_id,success,created_at,metadata) \
             VALUES($1,$2,$3,$4,$5,$6,$7,$8)",
        )
        .bind(i64_at(row, "id"))
        .bind(i64_at(row, "actor_user_id"))
        .bind(string_at(row, "action").unwrap_or_default())
        .bind(string_at(row, "target_type"))
        .bind(i64_at(row, "target_id"))
        .bind(bool_at(row, "success"))
        .bind(time_at(row, "created_at")?.unwrap_or_else(Utc::now))
        .bind(string_at(row, "metadata"))
        .execute(&mut *target)
        .await?;
        copied += 1;
    }
    Ok(copied)
}

async fn import_user_roles(
    source: &sqlx::SqlitePool,
    target: &mut sqlx::PgConnection,
) -> anyhow::Result<u64> {
    let rows = sqlx::query("SELECT * FROM user_roles")
        .fetch_all(source)
        .await?;
    let mut copied = 0u64;
    for row in &rows {
        sqlx::query(
            "INSERT INTO user_roles(user_id,role_name,granted_by_user_id,created_at) VALUES($1,$2,$3,$4) \
             ON CONFLICT (user_id, role_name) DO NOTHING",
        )
        .bind(i64_at(row, "user_id"))
        .bind(string_at(row, "role_name").unwrap_or_default())
        .bind(i64_at(row, "granted_by_user_id"))
        .bind(time_at(row, "created_at")?.unwrap_or_else(Utc::now))
        .execute(&mut *target)
        .await?;
        copied += 1;
    }
    Ok(copied)
}

async fn import_board_moderators(
    source: &sqlx::SqlitePool,
    target: &mut sqlx::PgConnection,
) -> anyhow::Result<u64> {
    let rows = sqlx::query("SELECT * FROM board_moderators")
        .fetch_all(source)
        .await?;
    let mut copied = 0u64;
    for row in &rows {
        sqlx::query(
            "INSERT INTO board_moderators(board_id,user_id,granted_by_user_id,created_at) VALUES($1,$2,$3,$4) \
             ON CONFLICT (board_id, user_id) DO NOTHING",
        )
        .bind(i64_at(row, "board_id"))
        .bind(i64_at(row, "user_id"))
        .bind(i64_at(row, "granted_by_user_id"))
        .bind(time_at(row, "created_at")?.unwrap_or_else(Utc::now))
        .execute(&mut *target)
        .await?;
        copied += 1;
    }
    Ok(copied)
}

async fn import_reports(
    source: &sqlx::SqlitePool,
    target: &mut sqlx::PgConnection,
) -> anyhow::Result<u64> {
    let rows = sqlx::query("SELECT * FROM reports")
        .fetch_all(source)
        .await?;
    let mut copied = 0u64;
    for row in &rows {
        sqlx::query(
            "INSERT INTO reports(id,reporter_user_id,target_type,target_id,reason,status,resolved_by_user_id,resolution_note,created_at,resolved_at) \
             VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)",
        )
        .bind(i64_at(row, "id"))
        .bind(i64_at(row, "reporter_user_id"))
        .bind(string_at(row, "target_type").unwrap_or_default())
        .bind(i64_at(row, "target_id"))
        .bind(string_at(row, "reason").unwrap_or_default())
        .bind(string_at(row, "status").unwrap_or_else(|| "open".to_string()))
        .bind(i64_at(row, "resolved_by_user_id"))
        .bind(string_at(row, "resolution_note"))
        .bind(time_at(row, "created_at")?.unwrap_or_else(Utc::now))
        .bind(time_at(row, "resolved_at")?)
        .execute(&mut *target)
        .await?;
        copied += 1;
    }
    Ok(copied)
}

/// Administrators predate the normalized role tables. Preserve the authority
/// that migration 010 granted them.
async fn backfill_owner_roles(target: &mut sqlx::PgConnection) -> anyhow::Result<u64> {
    let result = sqlx::query(
        "INSERT INTO user_roles(user_id,role_name,granted_by_user_id,created_at) \
         SELECT id, 'owner', NULL, created_at FROM users WHERE is_admin \
         ON CONFLICT (user_id, role_name) DO NOTHING",
    )
    .execute(&mut *target)
    .await?;
    Ok(result.rows_affected())
}

/// Advance identity sequences past the imported identifiers.
async fn reset_sequences(target: &mut sqlx::PgConnection) -> anyhow::Result<()> {
    for table in IDENTITY_TABLES {
        let sql = format!(
            "SELECT setval(pg_get_serial_sequence('{table}','id'), \
             COALESCE((SELECT MAX(id) FROM {table}), 0) + 1, false)"
        );
        sqlx::query(&sql).execute(&mut *target).await?;
    }
    Ok(())
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let options = parse_options()?;
    let target_label = veil_forum::store::redact_database_url(&options.database_url);

    let source = SqlitePoolOptionsT::new()
        .max_connections(1)
        .connect_with(
            SqliteConnectOptions::from_str(&format!("sqlite:{}", options.sqlite_path))?
                .read_only(true),
        )
        .await
        .with_context(|| format!("open SQLite database {}", options.sqlite_path))?;

    // Read (and validate) every timestamp before touching the target, so a
    // malformed row cannot leave a half-imported database behind.
    let mut expected: Vec<(&str, i64)> = Vec::new();
    for table in TABLES {
        if *table == "sessions" && !options.include_sessions {
            continue;
        }
        expected.push((table, count_rows_sqlite(&source, table).await?));
    }
    println!("Source: {}", options.sqlite_path);
    for (table, count) in &expected {
        println!("  {table:<18} {count}");
    }

    let target = PgPool::connect(&options.database_url)
        .await
        .with_context(|| format!("connect to PostgreSQL at {target_label}"))?;
    sqlx::migrate!("./migrations")
        .run(&target)
        .await
        .context("apply PostgreSQL migrations")?;

    if options.dry_run {
        let has_data = target_has_data(&target).await?;
        println!(
            "Dry run: target {} and {}",
            target_label,
            if has_data {
                "already contains forum data (--force would truncate it)"
            } else {
                "is empty"
            }
        );
        return Ok(());
    }

    // Everything that writes to the target happens in one transaction. A
    // malformed legacy row (a unique violation, a foreign key, a failed role
    // check) must roll the whole import back instead of leaving a truncated,
    // half-populated database behind.
    let mut tx = target.begin().await?;

    if target_has_data(&target).await? {
        if !options.force {
            anyhow::bail!(
                "target {target_label} already contains forum data; \
                 re-run with --force to replace it (existing rows are deleted)"
            );
        }
        println!("--force: clearing existing forum data in {target_label}");
        truncate_forum_tables(&mut tx).await?;
    } else {
        // Seed rows must not collide with imported rows.
        sqlx::query("TRUNCATE configs, roles CASCADE")
            .execute(&mut *tx)
            .await?;
        sqlx::query("INSERT INTO roles(name) VALUES ('owner'), ('admin'), ('moderator')")
            .execute(&mut *tx)
            .await?;
    }

    import_users(&source, &mut tx).await?;
    import_boards(&source, &mut tx).await?;
    import_configs(&source, &mut tx).await?;
    import_invite_codes(&source, &mut tx).await?;
    import_threads(&source, &mut tx).await?;
    import_posts(&source, &mut tx).await?;
    if options.include_sessions {
        import_sessions(&source, &mut tx).await?;
    }
    import_audit_logs(&source, &mut tx).await?;
    import_user_roles(&source, &mut tx).await?;
    import_board_moderators(&source, &mut tx).await?;
    import_reports(&source, &mut tx).await?;

    let granted = backfill_owner_roles(&mut tx).await?;
    if granted > 0 {
        println!("Restored owner role for {granted} administrator account(s)");
    }
    reset_sequences(&mut tx).await?;
    tx.commit().await?;

    // Statistics are collected after the rows are durable.
    sqlx::raw_sql("ANALYZE").execute(&target).await?;

    let mut failures = Vec::new();
    println!("Reconciliation:");
    for (table, expected_count) in &expected {
        let actual = count_rows_postgres(&target, table).await?;
        let ok = actual == *expected_count;
        println!(
            "  {:<18} source {:<8} target {:<8} {}",
            table,
            expected_count,
            actual,
            if ok { "ok" } else { "MISMATCH" }
        );
        if !ok {
            failures.push(*table);
        }
    }
    if !failures.is_empty() {
        anyhow::bail!("row counts differ for: {}", failures.join(", "));
    }

    println!("Import complete. Start veil-forum with:");
    println!("  veil-forum --database-url {}", target_label);
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_every_historical_timestamp_format() {
        // RFC3339 with nanoseconds and with offsets: every variant must resolve
        // to the same UTC instant, keeping the nanosecond precision.
        for (input, nanos) in [
            ("2026-08-26T08:19:02.853853123Z", 853_853_123),
            ("2026-08-26T08:19:02.123456Z", 123_456_000),
            ("2026-08-26T16:19:02.123456789+08:00", 123_456_789),
            ("2026-08-26T03:19:02.123456789-05:00", 123_456_789),
        ] {
            let parsed = parse_legacy_time(input).unwrap_or_else(|e| panic!("{input}: {e}"));
            let expected = format!("2026-08-26T08:19:02.{nanos:09}Z")
                .parse::<DateTime<Utc>>()
                .expect("expected instant");
            assert_eq!(parsed, expected, "{input}");
            assert_eq!(
                parsed.timestamp_nanos_opt().unwrap() % 1_000_000_000,
                nanos,
                "{input}"
            );
        }

        // Second precision, zero-nanosecond and legacy space-separated forms.
        let reference = "2026-08-26T08:19:02Z"
            .parse::<DateTime<Utc>>()
            .expect("instant");
        let seconds = parse_legacy_time("2026-08-26T08:19:02Z").expect("rfc3339 seconds");
        assert_eq!(seconds, reference);
        let zero_nanos = parse_legacy_time("2026-08-26T08:19:02.000000000Z").expect("zero nanos");
        assert_eq!(zero_nanos, reference);
        let legacy = parse_legacy_time("2026-08-26 08:19:02").expect("legacy format");
        assert_eq!(legacy, reference);
        let legacy_nanos =
            parse_legacy_time("2026-08-26 08:19:02.500000000").expect("legacy with nanos");
        assert_eq!(
            legacy_nanos.timestamp_nanos_opt().unwrap() % 1_000_000_000,
            500_000_000
        );
    }

    #[test]
    fn normalizes_offsets_to_utc() {
        let expected = "2026-08-26T08:19:02.123456789Z"
            .parse::<DateTime<Utc>>()
            .unwrap();
        for offset in ["Z", "+00:00", "-05:00", "+05:30", "+08:00", "-12:00"] {
            let shifted = match offset {
                "Z" | "+00:00" => "2026-08-26T08:19:02.123456789Z".to_string(),
                "-05:00" => "2026-08-26T03:19:02.123456789-05:00".to_string(),
                "+05:30" => "2026-08-26T13:49:02.123456789+05:30".to_string(),
                "+08:00" => "2026-08-26T16:19:02.123456789+08:00".to_string(),
                "-12:00" => "2026-08-25T20:19:02.123456789-12:00".to_string(),
                _ => unreachable!(),
            };
            let parsed = parse_legacy_time(&shifted).expect("valid offset");
            assert_eq!(parsed, expected, "offset {offset}");
        }
    }

    #[test]
    fn rejects_invalid_timestamps() {
        for input in ["", "not-a-timestamp", "2026-13-45T99:99:99Z", "26/08/2026"] {
            assert!(
                parse_legacy_time(input).is_err(),
                "{input:?} must be rejected"
            );
        }
    }
}
